- name: Install system dependencies for Playwright
  run: |
    sudo apt-get update
    sudo apt-get install -y \
      libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
      libgbm1 libgtk-3-0 libnspr4 libnss3 libxcomposite1 \
      libxdamage1 libxrandr2 xdg-utils libxss1 libasound2
