name: NEPSE LTP Checker

on:
  schedule:
    # Runs Sunday - Thursday at 3:30 PM Nepal Time (UTC+5:45)
    # 3:30 PM NPT = 09:45 AM UTC
    - cron: '45 9 * * 0-4'
  workflow_dispatch:

jobs:
  run_ltp_checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install system dependencies for Playwright
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 \
          libgbm1 libgtk-3-0 libnspr4 libnss3 libxcomposite1 \
          libxdamage1 libxrandr2 xdg-utils libxss1 libasound2

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: python -m playwright install firefox

    - name: Run LTP Checker Script
      run: python ltp_checker.py
