name: NEPSE LTP Checker

on:
  schedule:
    # Runs every Sunday to Thursday at 15:30 NPT (GMT+5:45)
    - cron: '45 9 * * 0-4'  # UTC 9:45 = 15:30 NPT
  workflow_dispatch:
  
jobs:
  check-nepse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install requests
      run: pip install requests

    - name: Run NEPSE checker
      run: python ltp_checker.py
