name: NEPSE LTP Checker

on:
  schedule:
    # Runs Sunday - Thursday at 3:30 PM NPT (Nepal Standard Time)
    # NPT is UTC+5:45. So, 3:30 PM NPT (15:30) is 9:45 AM UTC.
    # Cron format: min hour day_of_month month day_of_week
    # 0 = Sunday, 1 = Monday, ..., 4 = Thursday
    - cron: '45 9 * * 0-4'
  workflow_dispatch:
    # Allows you to manually trigger the workflow from the GitHub UI

jobs:
  run_ltp_checker:
    runs-on: ubuntu-latest # Uses a fresh Ubuntu virtual machine for each run

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version available

    - name: Create requirements.txt
      # This step creates the requirements.txt file on the runner
      # You should ensure your actual requirements.txt in your repo matches these,
      # or commit your requirements.txt directly to your repo.
      run: |
        echo "playwright" > requirements.txt
        echo "requests" >> requirements.txt

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Install dependencies from requirements.txt

    - name: Install Playwright browsers
      # The script uses Firefox, so we specifically install Firefox.
      run: python -m playwright install firefox

    - name: Run LTP Checker Script
      # The Discord Webhook URL is assumed to be hardcoded within ltp_checker.py
      # Therefore, no 'env:' block is needed here to pass it as a secret.
      run: python ltp_checker.py
