name: Nepse LTP Checker

on:
  schedule:
    # Schedule to run Sunday to Thursday at 3:30 PM GMT+5:45 (which is 09:45 UTC)
    # The cron expression is in UTC.
    # 3:30 PM GMT+5:45 is 09:45 AM UTC.
    # Days of the week: 0 (Sunday) to 4 (Thursday)
    - cron: '45 9 * * 0-4'
  workflow_dispatch: # This line adds the manual trigger option

jobs:
  run-ltp-checker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a recent Python version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright requests
        playwright install firefox # Install Firefox browser for Playwright

    - name: Run LTP Checker script
      run: python ltp_checker.py
